name = "vfld"
uuid = "9b22cc76-15b0-4f8e-a6fe-9d32a17c0c19"
authors = ["khintz"]
version = "0.1.0"

[compat]
julia = "1.5.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
